### ISSUE TITLE
typesafe moved from artifactory to bintray?

### ISSUE THREAD

**Issue by jtarn** [n8han/conscript#73]
```
localhost:.conscript jtarn$ jar -tf sbt-launch-0.13.7.jar
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.zip.ZipFile.<init>(ZipFile.java:116)
	at sun.tools.jar.Main.list(Main.java:1004)
	at sun.tools.jar.Main.run(Main.java:245)
	at sun.tools.jar.Main.main(Main.java:1177)

localhost:.conscript jtarn$ cat sbt-launch-0.13.7.jar
    `<html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx</center>
    </body>
   </html>`
```

I found sbt-launch at http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.7/sbt-launch.jar.

happy to help fix it if you need

**Comment by eed3si9n** [comment]
The URL of the launcher included in our release announcements and website should be used: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
instead of directly using Artifactory or Bintray (these could change in the future again).

**Comment by futurechimp** [comment]
Hi @eed3si9n, the `setup.sh` install script isn't working at the moment as a result of the URL changes. I'll try and bang out a pull request tomorrow to fix it, won't have time today.
